# Generated by Django 6.0.6 on 2026-07-13 21:33

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanctions', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
    ]
