# Generated by Django 6.0.6 on 2026-07-14 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanctions', '0002_enable_pg_trgm'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alias',
            unique_together={('entry', 'alias_type', 'alias_name')},
        ),
    ]
