# Generated by Django 6.0.6 on 2026-07-14 10:21

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanctions', '0003_alter_alias_unique_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alias',
            index=django.contrib.postgres.indexes.GinIndex(fields=['alias_name'], name='alias_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='sdnentry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='sdn_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
