# Generated by Django 6.0.6 on 2026-07-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctions', '0004_alias_alias_name_trgm_idx_sdnentry_sdn_name_trgm_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_entries', models.IntegerField()),
                ('new_entries', models.IntegerField()),
                ('removed_entries', models.IntegerField()),
                ('new_aliases', models.IntegerField()),
            ],
        ),
    ]
