# Generated by Django 6.0.6 on 2026-07-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctions', '0006_searchlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdnentry',
            name='source',
            field=models.CharField(default='OFAC', max_length=50),
        ),
        migrations.AlterField(
            model_name='sdnentry',
            name='uid',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='sdnentry',
            unique_together={('source', 'uid')},
        ),
    ]
