# Generated by Django 6.0.6 on 2026-07-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctions', '0007_sdnentry_source_alter_sdnentry_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='phonetic_key',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sdnentry',
            name='phonetic_key',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
