# Generated by Django 6.0.6 on 2026-07-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctions', '0008_alias_phonetic_key_sdnentry_phonetic_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='phonetic_key',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sdnentry',
            name='phonetic_key',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
