sample_un_xml = '''<?xml version="1.0"?>
<CONSOLIDATED_LIST>
<INDIVIDUALS>
<INDIVIDUAL>
<DATAID>6907993</DATAID>
<FIRST_NAME>ERIC</FIRST_NAME>
<SECOND_NAME>BADEGE</SECOND_NAME>
<UN_LIST_TYPE>DRC</UN_LIST_TYPE>
<INDIVIDUAL_ALIAS>
<QUALITY/>
<ALIAS_NAME/>
</INDIVIDUAL_ALIAS>
</INDIVIDUAL>
<INDIVIDUAL>
<DATAID>6908000</DATAID>
<FIRST_NAME>JOHN</FIRST_NAME>
<SECOND_NAME>DOE</SECOND_NAME>
<UN_LIST_TYPE>DRC</UN_LIST_TYPE>
<INDIVIDUAL_ALIAS>
<QUALITY>Good</QUALITY>
<ALIAS_NAME>JOHNNY DOE</ALIAS_NAME>
</INDIVIDUAL_ALIAS>
</INDIVIDUAL>
</INDIVIDUALS>
</CONSOLIDATED_LIST>'''


sample_un_xml_removed = '''<?xml version="1.0"?>
<CONSOLIDATED_LIST>
<INDIVIDUALS>
<INDIVIDUAL>
<DATAID>6907993</DATAID>
<FIRST_NAME>ERIC</FIRST_NAME>
<SECOND_NAME>BADEGE</SECOND_NAME>
<UN_LIST_TYPE>DRC</UN_LIST_TYPE>
</INDIVIDUAL>
</INDIVIDUALS>
</CONSOLIDATED_LIST>'''